#!/usr/bin/env python3
"""
Update the exif table with image dimensions from the CSV file generated by getImageDimensions.sh

Usage: python update_image_dimensions.py <csv-file> <database-file>
"""

import sys
import csv
import sqlite3
from pathlib import Path

def update_dimensions(csv_file, db_file):
    """Update ImageWidth and ImageHeight in the exif table"""

    if not Path(csv_file).exists():
        print(f"Error: CSV file '{csv_file}' not found")
        sys.exit(1)

    if not Path(db_file).exists():
        print(f"Error: Database file '{db_file}' not found")
        sys.exit(1)

    # Connect to database
    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()

    # Read CSV and update database
    update_count = 0
    skip_count = 0

    with open(csv_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)

        for row in reader:
            filename = row.get('FileName')
            width = row.get('ImageWidth')
            height = row.get('ImageHeight')

            # Skip rows without dimension data
            if not width or not height or width == '-' or height == '-':
                skip_count += 1
                continue

            try:
                width = int(width)
                height = int(height)
            except ValueError:
                skip_count += 1
                continue

            # Update the exif table
            cursor.execute("""
                UPDATE exif
                SET ImageWidth = ?, ImageHeight = ?
                WHERE FileName = ?
            """, (width, height, filename))

            if cursor.rowcount > 0:
                update_count += 1

    # Commit changes
    conn.commit()
    conn.close()

    print(f"Successfully updated {update_count} records")
    print(f"Skipped {skip_count} records (no dimension data)")

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: python update_image_dimensions.py <csv-file> <database-file>")
        sys.exit(1)

    csv_file = sys.argv[1]
    db_file = sys.argv[2]

    update_dimensions(csv_file, db_file)
